# Generated by Django 3.2.9 on 2021-12-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.CharField(choices=[('1Kg', '1Kg'), ('2Kg', '2Kg')], default='1Kg', max_length=120),
        ),
    ]
