# Generated by Django 3.2.9 on 2021-12-22 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20211222_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='primary',
            new_name='price',
        ),
    ]
