# Generated by Django 3.2.9 on 2021-12-30 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0010_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutdetails',
            name='province',
        ),
        migrations.AddField(
            model_name='checkoutdetails',
            name='delivery_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ShippingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_by', models.CharField(max_length=100, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(max_length=100, null=True)),
                ('name_of_receiver', models.CharField(max_length=100)),
                ('main_address', models.CharField(max_length=200)),
                ('secondary_address', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('delivery_address', models.CharField(max_length=100, null=True)),
                ('postal_code', models.CharField(max_length=12)),
                ('phone_number', models.CharField(max_length=12)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_on',),
                'abstract': False,
            },
        ),
    ]
