# Generated by Django 3.2.9 on 2021-12-22 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211222_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='identifier',
            new_name='username',
        ),
    ]
