# Generated by Django 3.2.9 on 2021-12-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20211229_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
            ],
            options={
                'db_table': 'subsucribers',
            },
        ),
    ]
