# Generated by Django 3.2.9 on 2021-12-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_newssubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newssubscription',
            name='email',
            field=models.EmailField(db_index=True, max_length=255),
        ),
    ]
